#spring.datasource.url: jdbc:mysql://localhost:3306/skillbox?useSSL=false&amp;serverTimezone=UTC
#spring.datasource.username: root
#spring.datasource.password: test
#spring.jpa.hibernate.ddl-auto: none
#
